import { DatabaseSchema, TableInfo, ColumnInfo } from '@/lib/api';
import { GenerationPlan, TableGenerationSpec, GenerationResult } from './types';
import { FakerProvider } from './faker-provider';
import { EnhancedPIIDetector } from '@/lib/db/pii-detector-enhanced';

export class DataGenerator {
  /**
   * Generate mock data based on the plan
   */
  static async generate(
    plan: GenerationPlan,
    schema: DatabaseSchema
  ): Promise<GenerationResult> {
    const generatedData: Map<string, any[]> = new Map();
    const warnings: string[] = [];

    for (const tableSpec of plan.tables) {
      const tableInfo = schema.tables.find(t => t.name === tableSpec.name);
      if (!tableInfo) {
        warnings.push(`Table ${tableSpec.name} not found in schema`);
        continue;
      }

      const rows = this.generateTableData(tableSpec, tableInfo, schema, generatedData);
      generatedData.set(tableSpec.name, rows);
    }

    const sql = this.buildSQL(plan, generatedData, schema);

    return {
      sql,
      rowsGenerated: Array.from(generatedData.values()).reduce((sum, rows) => sum + rows.length, 0),
      tables: Array.from(generatedData.entries()).map(([name, rows]) => ({
        name,
        rows: rows.length,
      })),
      warnings: warnings.length > 0 ? warnings : undefined,
    };
  }

  private static generateTableData(
    tableSpec: TableGenerationSpec,
    tableInfo: TableInfo,
    schema: DatabaseSchema,
    existingData: Map<string, any[]>
  ): any[] {
    const rows: any[] = [];
    const piiResults = EnhancedPIIDetector.detectPIISync(tableInfo.columns);

    for (let i = 0; i < tableSpec.count; i++) {
      const row: Record<string, any> = {};

      for (const column of tableInfo.columns) {
        // Skip auto-generated columns
        if (column.defaultValue?.includes('nextval') || column.defaultValue?.includes('gen_random_uuid')) {
          continue;
        }

        const constraint = tableSpec.constraints.find(c => c.column === column.name);
        const relationship = tableSpec.relationships.find(r => r.localColumn === column.name);
        const piiInfo = piiResults.find(p => p.columnName === column.name);

        if (relationship) {
          row[column.name] = this.generateRelationshipValue(relationship, existingData);
        } else if (constraint && constraint.rule === 'null_percentage') {
          row[column.name] = Math.random() < constraint.value 
            ? null 
            : FakerProvider.generateValue(column.name, column.type, piiInfo?.detectedType, constraint);
        } else {
          row[column.name] = FakerProvider.generateValue(
            column.name,
            column.type,
            piiInfo?.detectedType,
            constraint
          );
        }
      }

      rows.push(row);
    }

    return rows;
  }

  private static generateRelationshipValue(
    relationship: any,
    existingData: Map<string, any[]>
  ): any {
    const foreignRows = existingData.get(relationship.foreignTable);

    if (!foreignRows || foreignRows.length === 0) {
      if (relationship.strategy === 'existing' || relationship.strategy === 'random_existing') {
        throw new Error(
          `Cannot generate relationship: no data exists for ${relationship.foreignTable}. ` +
          `Generate ${relationship.foreignTable} first or use strategy 'generate'.`
        );
      }
      return null;
    }

    const randomRow = foreignRows[Math.floor(Math.random() * foreignRows.length)];
    return randomRow[relationship.foreignColumn];
  }

  private static buildSQL(
    plan: GenerationPlan,
    generatedData: Map<string, any[]>,
    schema: DatabaseSchema
  ): string {
    let sql = '-- Generated by MockData\n';
    sql += `-- Strategy: ${plan.strategy}\n`;
    sql += `-- ${plan.description}\n\n`;

    if (plan.strategy === 'truncate_insert') {
      sql += '-- Truncate tables (in reverse order to respect FKs)\n';
      for (let i = plan.tables.length - 1; i >= 0; i--) {
        sql += `TRUNCATE TABLE ${plan.tables[i].name} CASCADE;\n`;
      }
      sql += '\n';
    }

    for (const [tableName, rows] of generatedData.entries()) {
      if (rows.length === 0) continue;

      sql += `-- Insert ${rows.length} rows into ${tableName}\n`;
      
      const columns = Object.keys(rows[0]);
      const columnList = columns.join(', ');

      for (const row of rows) {
        const values = columns.map(col => this.formatValue(row[col])).join(', ');
        sql += `INSERT INTO ${tableName} (${columnList}) VALUES (${values});\n`;
      }

      sql += '\n';
    }

    return sql;
  }

  private static formatValue(value: any): string {
    if (value === null || value === undefined) {
      return 'NULL';
    }

    if (typeof value === 'string') {
      return `'${value.replace(/'/g, "''")}'`;
    }

    if (typeof value === 'boolean') {
      return value ? 'TRUE' : 'FALSE';
    }

    if (value instanceof Date) {
      return `'${value.toISOString()}'`;
    }

    if (typeof value === 'object') {
      return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
    }

    return String(value);
  }

  /**
   * Generate a preview with sample data (first 5 rows per table)
   */
  static async generatePreview(
    plan: GenerationPlan,
    schema: DatabaseSchema
  ): Promise<{ sampleData: any[], sqlPreview: string }> {
    const previewPlan = {
      ...plan,
      tables: plan.tables.map(t => ({ ...t, count: Math.min(t.count, 5) })),
    };

    const result = await this.generate(previewPlan, schema);

    return {
      sampleData: Array.from(new Map<string, any[]>().entries()).map(([tableName, rows]) => ({
        tableName,
        rows,
      })),
      sqlPreview: result.sql,
    };
  }
}
